### ISSUE TITLE
proposal for design

### ISSUE THREAD

**Issue by eladb** [construct-catalog/catalog#1]
1. query npmjs.org for modules with some label (`label:aws+cdk ` should be fine).
2. process each module and extract the `.jsii` manifest from it
3. generate a static reference documentation html page/s from the jsii manifest (we will open source the stuff we have for the aws cdk reference documentation).
4. put it in cdn under a stable name: i.e. `/module` and `/module/version`
5. post a tweet on twitter with the name of the module and a link to the page, use labels for hashtags and add something like `#construct #awscdk` so it's discoverable.

i think this could serve as a nice base layer. it is searchable, subscrible and even social.

what do you guys think?

**Comment by rhboyd** [comment]
I like it. I've completed 1 & 2, I'll push my local changes early this week.

I'm going to work on the static-site's front end this weekend to get a decent mock-up in front of people to start socializing the Catalog.

**Comment by eladb** [comment]
Exciting! What are you doing for rendering the module page? I was looking at open sourcing our reference documentation generator. Do you think it’s valuable or you prefer to build something new? Our current reference generator is not amazing, so if you think we can invest in something better, we could then adopt it for the reference. Even better, just point people to the catalog directly and kill the reference.

**Comment by rhboyd** [comment]
Plan is to break it up into 2 parts, the catalog and the detail pages. Catalog will be built around finding Constructs in specific languages and or using specific services/patterns. The detail page was going to have info for the source repo and author with whatever bits I can scrape out of the document generator.

I wasn't planning on doing anything super complicated for launch, probably just re-purpose an open source e-commerce template.

**Comment by rhboyd** [comment]
Also considering:

* RSS feeds for topics (language and service combinations for p0)
* Allowing people to opt-in to having their constructs republished on other package managers

**Comment by garnaat** [comment]
I've been out for a few weeks and so I'm out of the loop.  Is the strategy to use Twitter as the backing store?  For the social features (e.g. liking) and also for search?  For example, if I'm browsing through the static site and discover a construct that I like, can I "like it" from the static site?  If so, are we then just programmatically calling Twitter's API to do that?  Or is there another backing store that we are managing?

Also, is there any sort of doc that describes the goals of this construct catalog?

**Comment by rhboyd** [comment]
Hey Mitch!!! I think Corey Quinn would approve of the plan to use Twitter as a DB, but my goal was to allow people to create logins (via AWS Cognito) and we'd store their information in DynamoDB. The search capability would be independent of any particular user's interests and would be built by indexing existing constructs according to the jsii manifest that's produced.

I've started to outline the goals for the catalog in [the vision statement](https://github.com/CDK-User-Group/CDK-Construct-Catalog/blob/master/Vision.md) and I'd love any feedback.

**Comment by garnaat** [comment]
Hi Richard.

Good, I'm glad we are thinking of some auth on our side because I think there is some really valuable insight that could be gained if we know who users are.  Plus I think owning that data is good, as well.

**Comment by eladb** [comment]
I don't see why we need authentication for v1.0 - the goal initially s to have a centralized place for people to find construct libraries. I think the minimum amount of friction in accessing this information is desirable. People are not expected to publish modules directly to this, but rather publish modules to npm, and this system will just index them and make them searchable and viewable.

Yes, @garnaat, my idea was to use Twitter as the backing store, exactly like you described. I think we get everything we want from that: searchability, likes, comments, social features. I would even start by implementing just the indexing and rendering of the module page and publish each discovered module as a tweet with some hashtags. Then, we (or anyone) can build a UI on top of this.

**Comment by garnaat** [comment]
I think its fine if we want to see how far we can take it with this approach.  But I feel pretty strongly that ultimately we will want to manage identities and provide auth and store most of the data ourselves.  I just don't think we will be able to achieve a really nice user experience any other way.

**Comment by eladb** [comment]
Let's start by defining the requirements for V1.0, @rhboyd want to kick this off?

**Comment by rhboyd** [comment]
Yep. Will do. I'll create issues for V1.0 requirements and tag them so they're easy to find.
