### ISSUE TITLE
Ability to Twitter mention accounts

### ISSUE THREAD

**Issue by mbonig** [construct-catalog/catalog#13]
If we're going to buy into Twitter, let's go all the way. I'd like to be able to add a keyword (or other metadata in package.json) that would @mention an account. That way I can automatically get mentioned and linked to my personal Twitter account anytime I publish a construct.

**Comment by eladb** [comment]
Yes. Totally. For one, if your package description will include @mention, it will Just Work ™️. Furthermore I think there’s a formal way to specify a Twitter account in the “author” field (I saw npm has links to accounts) so the catalog can just mention that account

**Comment by mbonig** [comment]
I think the formal way would be nice. I'll submit a PR.

**Comment by mbonig** [comment]
PR:
https://github.com/construct-catalog/catalog/pull/14
