### ISSUE TITLE
Filter core packages

### ISSUE THREAD

**Issue by udondan** [construct-catalog/catalog#24]
I believe the catalog doesn't have to post about core CDK constructs. On every CDK release there is a Tsunami of Tweets. This is both, a bit pointless and distracting from new 3rd party constructs.

If there is an easy way to filter the core constructs, that would be great. :)

**Comment by eladb** [comment]
Yes, https://github.com/construct-catalog/catalog/pull/22 adds support for that. We just need to update the CDK's `package.json` files to include this stanza.

**Comment by eladb** [comment]
WIP ===^

**Comment by udondan** [comment]
Great, sorry, didn't see the PR, was only looking at the issues. Thanks for updating the core packages.
