### ISSUE TITLE
Twittering is broken since September 23

### ISSUE THREAD

**Issue by udondan** [construct-catalog/catalog#43]
No twitter updates since a week. The packages are indexed though, so it is not an npm search issue. 

I see on that day #30 got merged in, maybe that's related. cc @mbonig 

Though, generally, Twittering has been very slow since a good while. Packages got indexed in reasonable time but the Tweet got sent hours (like 5 hours or so) after the release.

**Comment by mbonig** [comment]
I had noticed the same. The PR of mine was just to add to the resource policy on the sns topic so I don't think that would have removed any access or caused issues.

**Comment by udondan** [comment]
Yup, I see nothing wrong with the PR. The trailing brace is a bit off so it first looked like the twitter creds are outside of the class now. But yeah, I just linked the PR bc of the timing. Maybe some side effect, caused in the deploy pipeline or whatever.

**Comment by eladb** [comment]
Let me see what I can dig from the logs. Sorry about that crap

**Comment by mbonig** [comment]
Twitter banned API access because of too many @mentions. Until that's cleared up the code has been commented out. Problem should be resolved with https://github.com/construct-catalog/catalog/pull/44

**Comment by udondan** [comment]
And now it's not indexing again. 😸 [0.74.0 of cdk-iam-floyd](https://www.npmjs.com/package/cdk-iam-floyd/v/0.74.0) had been released over 8 hours ago. Package available in npm index:

```
$ curl -s http://registry.npmjs.com/-/v1/search?text=cdk-iam-floyd | jq
{
  "objects": [
    {
      "package": {
        "name": "cdk-iam-floyd",
        "scope": "unscoped",
        "version": "0.74.0",
        "description": "AWS IAM policy statement generator with fluent interface for AWS CDK",
        "keywords": [
          "aws",
          "iam",
          "policy",
          "iam-floyd",
          "cdk",
          "aws-cdk"
        ],
        "date": "2020-10-02T01:23:16.247Z",
        "links": {
          "npm": "https://www.npmjs.com/package/cdk-iam-floyd",
          "homepage": "https://github.com/udondan/iam-floyd",
          "repository": "https://github.com/udondan/iam-floyd",
          "bugs": "https://github.com/udondan/iam-floyd/issues"
        },
        "author": {
          "name": "Daniel Schroeder",
          "url": "https://www.udondan.com/"
        },
        "publisher": {
          "username": "udondan",
          "email": "deemes79@googlemail.com"
        },
        "maintainers": [
          {
            "username": "udondan",
            "email": "deemes79@googlemail.com"
          }
        ]
      },
      "flags": {
        "unstable": true
      },
      "score": {
        "final": 0.35080411219152724,
        "detail": {
          "quality": 0.7135411175332294,
          "popularity": 0.05735745789969086,
          "maintenance": 0.3333333333333333
        }
      },
      "searchScore": 100000.305
    }
  ],
  "total": 1,
  "time": "Fri Oct 02 2020 09:20:43 GMT+0000 (UTC)"
}
```

**Comment by eladb** [comment]
We are still waiting to hear from Twitter

**Comment by mbonig** [comment]
Was everything redeployed after your PR yesterday? Shouldn't that have opened up Tweets again?

**Comment by udondan** [comment]
As I understand it, the account has been completely locked. It cannot tweet at all (via API?).

In the meantime, packages have been indexed now. So that has fixed itself. But someone with access to the logs should have a look why packages are not being indexed for several hours. No hurry there. It's not that I need it. Just a thing that doesn't run smooth. :)

**Comment by mbonig** [comment]
> Was everything redeployed after your PR yesterday? Shouldn't that have opened up Tweets again?

Ignore this... yeah we're not sending mentions but the API is still locked to read-only.

**Comment by eladb** [comment]
I received a reply from Twitter:

> We appreciate you reaching back out. Your account does not seem to be compromised in any way. The issue you're experiencing may be related to a recent issue we had to resolve with some accounts being mistakenly locked or limited.
>
> We have provided information about this issue [here](https://twitter.com/TwitterSupport/status/1308911550296662016?s=20) along with some steps to take on your end. Let us know if this helps. We look forward to hearing from you soon! Thanks, Twitter

**Comment by eladb** [comment]
I am still seeing "RESTRICTED TO API READ ACCESS ONLY" in developer.twitter.com and getting errors when trying to POST. Replied to twitter with a question on what to do.

**Comment by udondan** [comment]
I assume there has been no response from Twitter yet? I myself am waiting for Twitter response since weeks. I guess everyone has been assigned full time to flagging some losers tweets.

**Comment by eladb** [comment]
Okay, I created a new Twitter App. Let's see how this plays out.

**Comment by udondan** [comment]
Seems to work, thanks @eladb! Now that's gonna be a spammy day on Twitter 😸

**Comment by eladb** [comment]
Hopefully our rate limiter will kick in so it's not supposed to be too spammy.
