### ISSUE TITLE
Add ability to exclude official AWS libraries from search

### ISSUE THREAD

**Issue by mmcculloh-dms** [construct-catalog/catalog#96]
When viewing https://awscdk.io, I am occasionally far more interested in community-created libraries rather than those that AWS has made. Finding AWS-created ones is easy, but the inverse is not.

If there was a checkbox to exclude official AWS constructs or if it were possible to exclude results using a certain search pattern (like `-"@aws-cdk"`), it would be easier to find interesting construct libraries.

**Comment by eladb** [comment]
Yes. Agreed. I think generally we should just hide all core libraries.

Contributions are welcome

**Comment by mmcculloh-dms** [comment]
https://constructs.dev/ has this feature 🎉
